spring.application.name=pedido
spring.profiles.active=dev

server.port=8081

springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.jpa.open-in-view=false

cliente.service.base-url=http://localhost:8082
cliente.service.username=admin
cliente.service.password=1234
