spring.application.name=db_shopnow
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jackson.mapper.allow-coercion-of-scalars=false

server.port=8082
springdoc.swagger-ui.path=/doc/swagger-ui.html
pedido.service.base-url=http://localhost:8081
